# Generated by Django 2.1.8 on 2019-11-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='engtarget',
            options={'managed': False, 'verbose_name_plural': 'Engineer Target'},
        ),
        migrations.AlterModelOptions(
            name='motortechnician',
            options={'managed': False, 'verbose_name_plural': 'Motor Technician'},
        ),
        migrations.AlterModelOptions(
            name='rowstatus',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='servicecalltype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='servicedetails',
            options={'managed': False, 'verbose_name_plural': 'Service Details'},
        ),
        migrations.AlterModelOptions(
            name='territory',
            options={'managed': False, 'verbose_name': 'Territory'},
        ),
        migrations.AlterModelOptions(
            name='tsatarget',
            options={'managed': False, 'verbose_name_plural': 'TSA Target'},
        ),
        migrations.AlterModelOptions(
            name='userarea',
            options={'managed': False, 'verbose_name': 'Assign User Area'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False},
        ),
    ]
