# Generated by Django 2.1.8 on 2019-11-21 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(db_column='UserName', max_length=50)),
                ('Password', models.CharField(db_column='Password', max_length=50)),
            ],
            options={
                'db_table': 'AppUser',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('Id', models.AutoField(db_column='ServiceDetailsId', primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(db_column='CustomerName', default='N/A', max_length=100)),
                ('CustomerCode', models.CharField(db_column='CustomerCode', default='N/A', max_length=100)),
                ('Mobile', models.CharField(db_column='Mobile', default='N/A', max_length=20)),
                ('ServicePortFolio', models.CharField(db_column='ServicePortFolio', default='N/A', max_length=100)),
                ('ServiceCount', models.CharField(db_column='ServiceCount', default='N/A', max_length=100)),
                ('ServiceDemandDate', models.DateTimeField(db_column='ServiceDemandDate')),
                ('ServiceStartDate', models.DateTimeField(db_column='ServiceStartDate')),
                ('ServiceEndDate', models.DateTimeField(db_column='ServiceEndDate')),
                ('ServiceIncome', models.FloatField(db_column='ServiceIncome', default=0.0)),
                ('VisitDate', models.DateTimeField(db_column='VisitDate')),
                ('MobileCreatedDT', models.DateTimeField(auto_now_add=True, db_column='MobileCreatedDT')),
                ('MobileEditedDT', models.DateTimeField(auto_now_add=True, db_column='MobileEditedDT')),
                ('MobileLogCount', models.IntegerField(db_column='MobileLogCount', default=0)),
                ('MobileId', models.IntegerField(db_column='MobileId', default=0)),
                ('ServerInsertDateTime', models.DateTimeField(auto_now_add=True)),
                ('ServerUpdateDateTime', models.DateTimeField(auto_now=True)),
                ('ServiceRatting', models.CharField(db_column='ServiceRatting', default='0', max_length=20)),
                ('UserId', models.ForeignKey(db_column='AppUserId', on_delete=django.db.models.deletion.CASCADE, to='pumpservice.AppUser')),
            ],
            options={
                'verbose_name_plural': 'Service Details',
                'db_table': 'ServiceDetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('Id', models.AutoField(db_column='TerritoryID', primary_key=True, serialize=False)),
                ('Name', models.CharField(db_column='TerritoryName', max_length=100)),
                ('Code', models.CharField(db_column='TerritoryCode', max_length=50)),
            ],
            options={
                'verbose_name': 'Territory',
                'db_table': 'Territory',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='TerritoryId',
            field=models.ForeignKey(db_column='TerritoryId', default=1, on_delete=django.db.models.deletion.CASCADE, to='pumpservice.Territory'),
        ),
    ]
