# Generated by Django 2.1 on 2020-01-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumpservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetails',
            name='MobileCreatedDT',
        ),
        migrations.RemoveField(
            model_name='servicedetails',
            name='MobileEditedDT',
        ),
        migrations.RemoveField(
            model_name='servicedetails',
            name='MobileLogCount',
        ),
        migrations.RemoveField(
            model_name='servicedetails',
            name='ServiceEndDate',
        ),
        migrations.RemoveField(
            model_name='servicedetails',
            name='ServiceRatting',
        ),
        migrations.AddField(
            model_name='servicedetails',
            name='Latitude',
            field=models.DecimalField(db_column='Latitude', decimal_places=8, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='servicedetails',
            name='Longitude',
            field=models.DecimalField(db_column='Longitude', decimal_places=8, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='servicedetails',
            name='ProductModel',
            field=models.CharField(db_column='ProductModel', default='N/A', max_length=100),
        ),
    ]
